-- database/oracle/oracle_queries.sql

-- Create a user for Skycast Weather
CREATE USER skycast_weather IDENTIFIED BY skycast_password;

-- Grant necessary privileges to the user
GRANT CONNECT, RESOURCE, DBA TO skycast_weather;

-- Connect to the Skycast Weather user
CONNECT skycast_weather;

-- Create a table to store weather data
CREATE TABLE weather_data (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    location VARCHAR2(255) NOT NULL,
    humidity NUMBER NOT NULL,
    clear_sky NUMBER(1,0) NOT NULL,
    speed NUMBER NOT NULL,
    date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Insert sample data
INSERT INTO weather_data (location, humidity, clear_sky, speed)
VALUES ('Example City', 70, 1, 10);

-- Query to retrieve weather data
SELECT * FROM weather_data;
